# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  WORKING_DIR: IAAC/environment/dev
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Terraform"
  Terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip curl

      - name: Azure Login
        uses: Azure/login@v3
        with:
          creds:
          client-id: "ad128e01-6a61-45eb-bfc3-ecbc9a6effc0"
          tenant-id: "c0deb48d-3915-4822-8bb8-2de6950b5302"
          subscription-id: "3e435172-5e9c-4c87-9f88-72d810198f70"
          client-secret: "4qN8Q~wuaLpX3HkCa0DQSyskR7eOu7-YoXlCCdwl"


